# Generated by Django 5.1.6 on 2025-03-16 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Scrap yard', 'Scrap yard'), ('Meltshop', 'Meltshop'), ('Rolling mill', 'Rolling mill'), ('Plate mill', 'Plate mill'), ('250', '250'), ('Prosal', 'Prosal'), ('TKC', 'TKC'), ('Other', 'Other'), ('Unknown', 'Unknown')], max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_incident', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('Scrap yard', 'Scrap yard'), ('Meltshop', 'Meltshop'), ('Rolling mill', 'Rolling mill'), ('Plate mill', 'Plate mill'), ('250', '250'), ('Prosal', 'Prosal'), ('TKC', 'TKC'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='Unknown', max_length=100)),
                ('area', models.CharField(default=1, max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
