# Generated by Django 5.1.6 on 2025-03-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='area_name',
        ),
    ]
