# Generated by Django 5.1.6 on 2025-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_rename_name_area_area_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
    ]
